sonar.projectKey=peterQin18_openapi-ktor-gradle-plugin
sonar.organization=peterqin18
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.java.binaries=build/classes/kotlin/main
sonar.java.test.binaries=build/classes/kotlin/test
